name: Build Psych Online With Mac OS

on: workflow_dispatch

jobs:
  buildAndroid:
    runs-on: macos-15 #Use mac os for lower compiling time (this matters if you're not compiling the project on local too)

    steps:
      - uses: actions/checkout@v2
      - name: Retrieve Cache
        uses: actions/cache@v4
        with:
          path: |
            export/release/android/haxe
            export/release/android/obj
          key: ${{ runner.os }}-cache

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.6

      - name: Setup Java JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
<<<<<<< HEAD
          ndk-version: r29-beta1
=======
          name: windowsBuild
          path: export/release/windows/bin
  buildMac:
    runs-on: macos-14
>>>>>>> 6d320d34793cbb791cf739c6dc567970cca5c8fc

      - name: Install Haxelib
        run: |
          haxelib setup ~/haxelib
          haxelib install hxcpp > /dev/null --quiet
          haxelib install hmm --quiet
          haxelib run hmm install
          haxelib run lime config ANDROID_SDK $ANDROID_HOME
          haxelib run lime config ANDROID_NDK_ROOT ${{ steps.setup-ndk.outputs.ndk-path }}
          haxelib run lime config JAVA_HOME $JAVA_HOME_17_arm64
          haxelib run lime config ANDROID_SETUP true

      - name: Setup HXCPP Tools
        run: |
          cd .haxelib/hxcpp/git/tools/hxcpp
          haxe compile.hxml
          cd ../../../../..

      - name: Compile
<<<<<<< HEAD
        run: haxelib run lime build Project.xml android -D ONLY_ARM64 -D HXCPP_M64

=======
        run: arch -x86_64 haxelib run lime build mac --app-version="4.0.0-${{ github.run_id}}"
>>>>>>> 6d320d34793cbb791cf739c6dc567970cca5c8fc
      - name: Publish Artifact
        uses: actions/upload-artifact@main
        with:
          name: androidBuild
          path: 'export/release/android/bin/app/build/outputs/apk/release/*.apk'
          if-no-files-found: error