name: Build Psych Online

on: workflow_dispatch
jobs:
  buildAndroid:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
    
      - name: Retrieve Cache
        uses: actions/cache@v4
        with:
          path: |
            export/release/android/haxe
            export/release/android/obj
          key: ${{ runner.os }}-cache

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.2
    
      - name: Setup Java JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r29-beta1 # 29.0.13113456
 
      - name: Install Haxelib
        run: |
          sudo apt-get install libvlc-dev
          sudo apt-get install libvlccore-dev
          haxelib setup ~/haxelib
          haxelib install hxcpp > /dev/null --quiet
          haxelib install hmm --quiet
          haxelib run hmm install
          haxelib run lime config ANDROID_SDK $ANDROID_HOME
          haxelib run lime config ANDROID_NDK_ROOT ${{steps.setup-ndk.outputs.ndk-path}}
          haxelib run lime config JAVA_HOME $JAVA_HOME
          haxelib run lime config ANDROID_SETUP true

      - name: Setup HXCPP Tools
        run: |
          cd .haxelib/hxcpp/git/tools/hxcpp
          haxe compile.hxml
          cd ../../../../..
      - name: Create Version Tag
        run: echo "${{github.run_id}}" > VERSION
      - name: Compile
        run: haxelib run lime build Project.xml android -D HXCPP_M64 --app-version="4.0.0-${{ github.run_id}}"
      - name: Publish Artifact
        uses: actions/upload-artifact@v4
        with:
          name: androidBuild (experimental)
          path: 'export/release/android/bin/app/build/outputs/apk'
