name: Build Psych Online For Android

on: workflow_dispatch

jobs:
  buildAndroid:
    runs-on: macos-15 #Use mac os for lower compiling time (this matters if you're not compiling the project on local too)
    steps:
      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.2

      - name: Setup Android NDK
        id: setup-ndk
        uses: nttld/setup-ndk@main
        with:
          ndk-version: r27c

      - name: Install Libraries
        run: |
          haxelib install hmm --quiet
          haxelib run hmm install --quiet

      - name: Configure Android
        if: inputs.name == 'Android'
        run: |
          haxelib run lime config ANDROID_SDK $ANDROID_HOME
          haxelib run lime config ANDROID_NDK_ROOT ${{ steps.setup-ndk.outputs.ndk-path }}
          haxelib run lime config JAVA_HOME $JAVA_HOME_17_arm64
          haxelib run lime config ANDROID_SETUP true

      - name: Install Libraries
        run: |
          haxelib install hmm --quiet
          haxelib run hmm install --quiet

      - name: Compile
        run: haxelib run lime build android -D ONLY_ARM64
        
      - name: Publish Artifact
        uses: actions/upload-artifact@main
        with:
          name: androidBuild
          path: 'export/release/android/bin/app/build/outputs/apk/release/*.apk'
          if-no-files-found: error